added navigation component
nikhiljugale007/Vercel-UI pull request #15
Opened 2022-02-06 12:11 UTC by nikhiljugale007

Review navigation component

2022-02-06 12:20 UTC, Naman-Saxena1 requested changes
You can give some left and right padding to nav, as user profile looks too close to corner.

2022-02-06 14:19 UTC, nikhiljugale007 commented
> You can give some left and right padding to nav, as user profile looks too close to corner.

added 16 px padding to left and right.

2022-02-07 05:58 UTC, anasm11 commented
Good design. Looks good to merge.

2022-02-07 06:47 UTC, Ankur9669 approved these changes
Awesome!!!. The navbar is looking great you can go ahead and merge it

2022-02-07 06:47 UTC, Ankur9669 commented on component-lib/navigation.html
> +							</code>
You can give left right margin to your iframe, because on mobile screens it is sticked to both the sides

2022-02-07 13:24 UTC, nikhiljugale007 commented on component-lib/navigation.html
> +							</code>
added that in other PR (slider component PR ) it will get updated once I merge that. Thanks.

2022-02-07 13:24 UTC, merged