added slider component
nikhiljugale007/Vercel-UI pull request #16
Opened 2022-02-06 12:11 UTC by nikhiljugale007

Review slider component

2022-02-06 17:15 UTC, gauravsinhaweb requested changes

2022-02-06 17:15 UTC, gauravsinhaweb commented on component-lib/slider.html
> +							<img class="img-round" src="./logo.png" />
use alt in img tag

2022-02-06 17:17 UTC, nikhiljugale007 commented on component-lib/slider.html
> +							<img class="img-round" src="./logo.png" />
okay. I will add.

2022-02-07 05:54 UTC, anasm11 commented
The square slider doesnt seem to work. Rest all looks good to merge.

2022-02-07 05:55 UTC, Naman-Saxena1 commented
> The square slider doesnt seem to work. Rest all looks good to merge.

+1 Code looks fine but slider is not working in Preview.

2022-02-07 13:11 UTC, nikhiljugale007 commented
> The square slider doesnt seem to work. Rest all looks good to merge.

It is working, just that it's taking a little time to load CSS I guess. 
On hover, the curser changes to the pointer. 
Can you check again?

2022-02-07 13:13 UTC, nikhiljugale007 commented on component-lib/slider.html
> +							<img class="img-round" src="./logo.png" />
Added alt tag in new commit

2022-02-08 03:22 UTC, merged